config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  draw :turbo

  # Jumpstart views
  if Rails.env.development? || Rails.env.test?
    mount Jumpstart::Engine, at: "/jumpstart"
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require "sidekiq/web"
        mount Sidekiq::Web => "/sidekiq"
      end

      resources :announcements
      resources :users
      namespace :user do
        resources :connected_accounts
      end
      resources :accounts
      resources :account_users
      resources :plans
      namespace :pay do
        resources :charges
        resources :subscriptions
      end

      root to: "dashboard#show"
    end
  end

  # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :auth
      resource :me, controller: :me
      resource :password
      resources :accounts
      resources :users
      resources :notification_tokens, only: :create
    end
  end

  # User account
  devise_for :users,
    controllers: {
      masquerades: "jumpstart/masquerades",
      omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
      sessions: "users/sessions"
    }
  devise_scope :user do
    get "session/otp", to: "sessions#otp"
  end

  resources :announcements, only: [:index]
  resources :api_tokens
  resources :accounts do
    member do
      patch :switch
    end

    resource :transfer, module: :accounts
    resources :account_users, path: :members
    resources :account_invitations, path: :invitations, module: :accounts
  end
  resources :account_invitations

  # Payments
  resource :card
  resource :subscription do
    patch :info
    patch :pause
    patch :resume
  end
  resources :charges

  namespace :account do
    resource :password
  end
  resources :notifications, only: [:index, :show]
  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resource :two_factor, controller: :two_factor do
      get :backup_codes
      get :verify
    end
    resources :connected_accounts
  end

  namespace :action_text do
    resources :embeds, only: [:create], constraints: {id: /[^\/]+/} do
      collection do
        get :patterns
      end
    end
  end

  scope controller: :static do
    get :about
    get :terms
    get :privacy
    get :pricing
  end

  post :sudo, to: "users/sudo#create"

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "dashboard#show", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  root to: "static#index"
end

app/controllers/admin/pay/subscriptions_controller.rb
module Admin
  class Pay::SubscriptionsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Pay::Subscription.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Pay::Subscription.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :require_payments_enabled
  before_action :authenticate_user_with_sign_up!
  before_action :require_account
  before_action :require_current_account_admin, except: [:show]
  before_action :set_plan, only: [:new]
  before_action :set_subscription, only: [:edit, :update]

  def show
  end

  def new
    if Jumpstart.config.stripe? && @plan.trial_period_days.to_i > 0
      @setup_intent = current_account.processor&.stripe? ? current_account.payment_processor.create_setup_intent : Stripe::SetupIntent.create
    end
  end

  def create
    current_account.assign_attributes(subscription_params)
    @plan = Plan.without_free.find(current_account.plan) # Get the Stripe or Braintree specific ID
    processor_id = @plan.processor_id(current_account.processor)
    current_account.subscribe(plan: processor_id, trial_period_days: @plan.trial_period_days)
    redirect_to root_path, notice: t(".created")
  rescue Pay::ActionRequired => e
    redirect_to pay.payment_path(e.payment.id)
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :new, status: :unprocessable_entity
  end

  def edit
  end

  def update
    current_account.assign_attributes(subscription_params)

    # Get the Stripe or Braintree specific ID
    @plan = Plan.find(current_account.plan)
    processor_id = @plan.processor_id(current_account.processor)

    @subscription.swap(processor_id)
    redirect_to subscription_path
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :edit, status: :unprocessable_entity
  end

  def resume
    current_account.subscription.resume
    redirect_to subscription_path, notice: t(".resumed")
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show, status: :unprocessable_entity
  end

  def pause
    current_account.subscription.pause
    redirect_to subscription_path
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show
  end

  def destroy
    current_account.subscription.cancel

    current_account.update(card_type: nil, card_last4: nil, card_exp_month: nil, card_exp_year: nil) if current_account.subscription.paddle?

    # Optionally, you can cancel immediately
    # current_account.subscription.cancel_now!

    redirect_to subscription_path
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :show, status: :unprocessable_entity
  end

  def info
    current_account.update(subscription_params)
    redirect_to subscription_path, notice: t(".info_updated")
  end

  private

  def subscription_params
    params.require(:account).permit(:card_token, :plan, :processor, :extra_billing_info)
  end

  def require_account
    redirect_to new_user_registration_path unless current_account
  end

  def require_payments_enabled
    return if Jumpstart.config.payments_enabled?
    flash[:alert] = "Jumpstart must be configured for payments before you can manage subscriptions."
    redirect_back(fallback_location: root_path)
  end

  def set_plan
    @plan = Plan.without_free.find(params[:plan])
  rescue ActiveRecord::RecordNotFound
    redirect_to pricing_path
  end

  def set_subscription
    @subscription = current_account.subscription
    redirect_to subscription_path if @subscription.nil?
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
  def braintree_env
    Rails.env.production? ? "production" : "sandbox"
  end

  def payment_method_details(object)
    if object.paypal?
      "#{object.card_type.titleize} #{object.card_last4}"
    elsif object.paddle? && object.card_type == "PayPal"
      object.card_type.titleize.to_s
    else
      "#{object.card_type.titleize} ending in #{object.card_last4}"
    end
  end
end

app/views/subscriptions/_billing_info.html.erb
<h3><%= t ".extra_billing_info" %></h3>
<div class="flex" data-controller="toggle">
  <div class="flex-1">
    <div class="text-gray-700 mt-2"><%= t ".additional_information" %></div>

    <%= form_with model: current_account, url: info_subscription_path, html: { class: "hidden mt-4", data: { toggle_target: "toggleable" }} do |f| %>
      <div class="form-group">
        <%= f.label :extra_billing_info %>
        <%= f.text_area :extra_billing_info, class: "form-control", placeholder: true %>
      </div>

      <div class="form-group">
        <%= f.button t(".save_info"), class: "btn btn-primary", data: { disable_with: disable_with(t(".saving"))} %>
      </div>
    <% end %>
  </div>

  <div>
    <%= link_to t(".add_info"), "#", class: "btn btn-link text-gray-700", data: { action: "click->toggle#toggle" } %>
  </div>
</div>
<div class="text-gray-600">
  <%= current_account.extra_billing_info %>
</div>

app/views/subscriptions/_cancel.html.erb
<% if current_account.subscription && !current_account.subscription.cancelled? %>
  <hr class="border-b my-8" />
  <h3><%= t ".title" %></h3>
  <div class="flex">
    <div class="flex-1 mt-2 text-gray-700">
      <div class="font-bold"><%= t ".description", product: Jumpstart.config.application_name %></div>
      <div><%= t ".help_html", link: mail_to(Jumpstart.config.support_email, t(".contact_us"), subject: t(".subject", product: Jumpstart.config.application_name), class: "underline text-blue-600") %></div>
    </div>

    <div>
      <%= link_to t(".button"), subscription_url, method: :delete, class: "btn btn-link text-gray-700", data: { confirm: t("are_you_sure"), disable_with: disable_with(t(".cancelling")) } %>
    </div>
  </div>
<% end %>

app/views/subscriptions/_charges.html.erb
<h3><%= t ".invoices" %></h3>
<p class="mt-2 text-gray-700"><%= t ".invoices_description" %></p>

<% if current_account.charges.exists? %>
  <table class="w-full">
    <thead>
      <tr>
        <th class="p-3 uppercase text-left text-xs text-gray-700"><%= t ".date" %></th>
        <th class="p-3 uppercase text-left text-xs text-gray-700"><%= t ".payment_method" %></th>
        <th class="p-3 uppercase text-left text-xs text-gray-700"><%= t ".amount" %></th>
        <th class="p-3 uppercase text-left text-xs text-gray-700"><%= t ".receipt" %></th>
      </tr>
    </thead>

    <tbody>
      <% current_account.charges.each do |charge| %>
        <tr class="group border-t border-gray-400 hover:bg-gray-200">
          <td class="p-3"><%= charge.created_at.strftime("%B %e, %Y") %></td>
          <td class="p-3"><i class="fab fa-cc-<%= charge.card_type.downcase %> text-gray-700"></i> <%= payment_method_details(charge) %></td>
          <td class="p-3"><%= number_to_currency charge.amount / 100.0 %></td>
          <td class="p-3">
            <%= link_to t(".view"), charge.paddle_receipt_url, target: "_blank" if Jumpstart.config.paddle? %>
            <%= link_to render_svg("icons/download"), charge_path(charge, format: :pdf) unless Jumpstart.config.paddle? %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/subscriptions/_current_plan.html.erb
<h3><%= t(".title") %></h3>

<% if current_account.subscription&.on_trial? %>
  <%= render partial: "subscriptions/trial_details" %>
<% end %>

<% if current_account.subscription&.cancelled? %>
  <% if current_account.subscription.on_grace_period? && !Jumpstart.config.paddle? %>
    <div class="flex">
      <div class="flex-1 mt-2">
        <%= t ".subscription_ends_html", date: current_account.subscription.ends_at.strftime("%B %d, %Y") %>
      </div>

      <div>
        <%= form_for current_account, url: resume_subscription_url, method: :patch do |f| %>
          <%= f.button t(".resume"), class: "btn btn-tertiary", data: { disable_with: disable_with(t(".resuming")) } %>
        <% end %>
      </div>
    </div>

  <% else %>
    <p><%= t ".resubscribe_html", link: link_to(t(".resubscribe"), new_subscription_path, class: "underline text-blue-500") %></p>
  <% end %>

<% elsif current_account.subscription&.paused? %>
  <div class="flex">
    <div class="flex-1 mt-2">
      <% if current_account.subscription.on_grace_period? %>
        <%= t ".subscription_pauses_html", date: current_account.subscription.paddle_paused_from.strftime("%B %d, %Y") %>
      <% else %>
        <%= t ".subscription_paused_html" %>
      <% end %>
    </div>

    <div>
      <%= form_for current_account, url: resume_subscription_url, method: :patch do |f| %>
        <%= f.button t(".resume"), class: "btn btn-tertiary", data: { disable_with: disable_with(t(".resuming")) } %>
      <% end %>
    </div>
  </div>

<% elsif current_account.subscription&.active? %>

  <div class="flex">
    <div class="flex-1 mt-2">
      <div><%= t ".current_plan_html", plan: current_account.subscription.plan.name %></div>
    </div>
    <div>
      <%= link_to t(".change_plan"), edit_subscription_path, class: "btn btn-link text-gray-700" %>
    </div>
  </div>
<% else %>
  <div class="flex">
    <div class="flex-1 mt-2 text-gray-700"><%= t ".not_subscribed" %></div>
    <div><%= link_to t(".choose_plan"), pricing_path, class: "btn btn-primary" %></div>
  </div>
<% end %>

<hr class="border-b my-8" />

<%= render partial: "subscriptions/payment_method" %>

<hr class="border-b my-8" />

<%# Paddle: Extra payment details live in Paddle, not our app %>
<% unless current_account.subscription&.paddle? %>
  <%= render partial: "subscriptions/billing_info" %>
<% end %>

<hr class="border-b my-8" />

<%= render partial: "subscriptions/charges" %>
<%= render partial: "subscriptions/pause" %>
<%= render partial: "subscriptions/cancel" %>

app/views/subscriptions/_pause.html.erb
<%# Pause is only available with Paddle subscriptions %>
<% if Jumpstart.config.paddle? && current_account.subscription && !current_account.subscription.paused? %>
  <hr class="border-b my-8" />
  <h3><%= t ".pause.title" %></h3>
  <div class="flex">
    <div class="flex-1 mt-2 text-gray-700">
      <div class="font-bold"><%= t ".pause.description" %></div>
      <div><%= t ".pause.note" %></div>
    </div>

    <div>
      <%= form_for current_account, url: pause_subscription_url, method: :patch do |f| %>
        <%= f.button t(".pause.button"), class: "btn btn-link text-gray-700", data: { disable_with: disable_with(t(".pause.pausing")) } %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/subscriptions/_payment_method.html.erb
<h3><%= t ".payment_method" %></h3>

<div class="flex">
  <div class="flex-1 mt-2">
    <% if current_account.card_type? %>
      <i class="fab fa-cc-<%= current_account.card_type.downcase %> text-gray-700"></i> <%= payment_method_details(current_account) %>
    <% else %>
      <p class="text-gray-700"><%= t ".no_card" %></p>
    <% end %>
  </div>
  <div>
    <%= link_to t(".update_payment_method"), edit_card_path, class: "btn btn-link text-gray-700" %>
  </div>
</div>

app/views/subscriptions/_plan.html.erb
<div class="lg:w-1/3 w-full text-center p-8 border shadow m-4 rounded-lg bg-white">
  <h5><%= plan.name %></h5>
  <div>
    <sup class="text-xl">$</sup>
    <span class="text-4xl"><%= plan.amount / 100 %></span>
    <span class="text-lg">/ <%= plan.interval %></span>
  </div>

  <div class="my-2 text-center">
    <% Array.wrap(plan.features).each do |plan_feature| %>
      <p class="mb-4"><%= plan_feature %></p>
    <% end %>
  </div>

  <%# Yield for custom actions at the bottom %>
  <%= yield %>
</div>

app/views/subscriptions/_trial_details.html.erb
<div class="flex items-center bg-orange-200 text-orange-600 text-sm font-bold px-4 py-3 my-4" role="alert">
  <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
  <p><%= t ".trial_ends", days: time_ago_in_words(current_account.subscription.trial_ends_at) %></p>
</div>

app/views/subscriptions/edit.html.erb
<% if @subscription.on_trial? %>
  <div class="flex justify-center items-center bg-orange-200 text-orange-600 text-sm font-bold px-4 py-3 mb-4" role="alert">
    <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
    <p><%= t(".trial_ends", days: time_ago_in_words(@subscription.trial_ends_at)) %></p>
  </div>
<% end %>

<div class="container m-auto my-10">
  <div class="flex flex-wrap justify-center">
    <div class="text-center">
      <h1><%= t(".title") %></h1>
      <p class="text-xl"><%= t(".description") %></p>
    </div>
  </div>

  <div data-controller="pricing" class="flex flex-wrap items-center justify-center">

    <div data-pricing-target="toggle" class="inline-block rounded-full bg-tertiary-500 py-2 px-1 text-white my-8">
      <a data-action="click->pricing#switch" data-pricing-target="frequency" data-frequency="monthly" class="cursor-pointer py-2 px-4 rounded-full">
        <%= t(".monthly") %>
      </a>
      <a data-action="click->pricing#switch" data-pricing-target="frequency" data-frequency="yearly" class="cursor-pointer py-2 px-4 rounded-full">
        <%= t(".yearly") %>
      </a>
    </div>

    <div class="w-full lg:px-0 px-2">
      <div data-pricing-target="plans" data-frequency="monthly" class="flex flex-wrap items-center justify-center -mx-4">
        <% Plan.monthly.each do |plan| %>
          <%= render layout: "subscriptions/plan", locals: { plan: plan } do %>
            <% if @subscription.plan == plan %>
              <div class="btn btn-white"><%= t(".current_plan") %></div>
            <% else %>
              <%= form_with model: current_account, url: subscription_url do |f| %>
                <%= f.hidden_field :plan, value: plan.id %>
                <%= f.button t(".change_plan"), class: "btn btn-tertiary", data: { disable_with: t(".processing") } %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div data-pricing-target="plans" data-frequency="yearly" class="hidden flex-wrap items-center justify-center -mx-4">
        <% Plan.yearly.each do |plan| %>
          <%= render layout: "subscriptions/plan", locals: { plan: plan } do %>
            <% if @subscription.plan == plan %>
              <div class="btn btn-white"><%= t(".current_plan") %></div>
            <% else %>
              <%= form_with model: current_account, url: subscription_url do |f| %>
                <%= f.hidden_field :plan, value: plan.id %>
                <%= f.button t(".change_plan"), class: "btn btn-tertiary", data: { disable_with: t(".processing") } %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/subscriptions/new.html.erb
<div class="shadow-lg rounded-lg flex flex-col sm:flex-row lg:w-1/2 mx-auto my-8 bg-white">
  <div class="sm:w-2/3 p-8">
    <h1><%= t(".title") %></h1>

    <hr class="border-b my-8" />

    <div class="flex items-center my-8">
      <%= account_avatar current_account, class: "h-10 w-10 rounded-full mr-4" %>
      <h4><%= current_account.name %></h4>
    </div>

    <div data-controller="toggle">
      <% if current_account.card_last4? %>
        <div data-toggle-target="toggleable">
          <div class="flex mb-8">
            <div class="flex-1">
              <label><%= t(".payment_method") %></label>
              <i class="fab fa-cc-<%= current_account.card_type.downcase %> text-gray-700"></i> <%= payment_method_details(current_account) %>
            </div>
            <%= link_to t(".change"), "#", class: "text-primary text-sm mt-6", data: { action: "click->toggle#toggle" } %>
          </div>

          <%= form_with model: current_account, url: subscription_path, method: :post do |f| %>
            <%= f.hidden_field :plan, value: @plan.id if @plan.present? %>
            <%= f.button t(".subscribe"), id: 'submit-button', class: "btn btn-primary", data: { action: "click->stripe#submit", disable_with: disable_with(t(".processing")) } %>
          <% end %>
        </div>
      <% end %>

      <%= tag.div class: ("hidden" if current_account.card_last4?), data: { toggle_target: "toggleable" } do %>
        <%= render 'subscriptions/forms/stripe'    if Jumpstart.config.stripe? %>
        <%= render 'subscriptions/forms/braintree' if Jumpstart.config.braintree? %>
        <%= render 'subscriptions/forms/paypal'    if Jumpstart.config.paypal? %>
        <%= render 'subscriptions/forms/paddle'    if Jumpstart.config.paddle? %>
      <% end %>
    </div>

    <div class="text-sm text-center mt-8">
      <%= render_svg "icons/question", styles: "fill-current text-gray-500 w-4 h-4 inline-block" %>
      <%= t(".help") %>
      <span class="text-gray-600">
        <%= t(".contact_html", link: mail_to(Jumpstart.config.support_email, t(".contact_support"), subject: t(".contact_subject", product: Jumpstart.config.application_name), class: "text-gray-800 underline")) %>
      </span>
    </div>
  </div>

  <div class="sm:w-1/3 p-8 bg-blue-700 text-white rounded-b-lg sm:rounded-b-none sm:rounded-r-lg">
    <div class="text-lg"><%= @plan.name %></div>

    <div class="my-3">
      <sup class="text-xl">$</sup>
      <% if Jumpstart.config.paddle? %>
        <span class="text-5xl" id="recurringTotal"><i class="fas fa-circle-notch fa-spin"></i></span>
      <% else %>
        <span class="text-5xl"><%= @plan.amount / 100 %></span>
      <% end %>
      <span class="text-lg">/ <%= @plan.interval %></span>
    </div>
    <div><%= t(".renews_html", interval: @plan.interval) %></div>

    <br />

    <% @plan.features.each do |plan_feature| %>
      <div class="mb-2"><i class="far fa-check-circle text-blue-400"></i> <%= plan_feature %></div>
    <% end %>

    <hr class="my-8 border-b border-blue-600" />

    <div class="mb-1"><%= t(".testimonial", product: Jumpstart.config.application_name) %></div>
    <div class="flex items-center pt-2">
      <img class="block h-8 rounded-full mx-auto mb-4 sm:mb-0 sm:mr-4 sm:ml-0" src="https://avatars1.githubusercontent.com/u/67093?s=40&v=4" alt="">
      <p class="leading-tight">Chris Oliver</p>
    </div>
  </div>
</div>

app/views/subscriptions/show.html.erb
<div class="flex flex-wrap my-4 lg:px-4">
  <div class="lg:w-1/4 w-full p-4">
    <%= render partial: "shared/account_navbar" %>
  </div>

  <div class="lg:w-3/4 w-full p-4">
    <div class="lg:p-10 p-4 bg-white rounded-lg border border-gray-300">
      <h1 class="h2 mb-2"><%= t(".title") %></h2>

      <% if account_admin?(current_account, current_user) %>
        <%= render "current_plan" %>
      <% else %>
        <p><%= t(".contact_admin", account: current_account.name) %></p>
      <% end %>
    </div>
  </div>
</div>