config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  draw :turbo

  # Jumpstart views
  if Rails.env.development? || Rails.env.test?
    mount Jumpstart::Engine, at: "/jumpstart"
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Administrate
  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      if defined?(Sidekiq)
        require "sidekiq/web"
        mount Sidekiq::Web => "/sidekiq"
      end

      resources :announcements
      resources :users
      namespace :user do
        resources :connected_accounts
      end
      resources :accounts
      resources :account_users
      resources :plans
      namespace :pay do
        resources :charges
        resources :subscriptions
      end

      root to: "dashboard#show"
    end
  end

  # API routes
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resource :auth
      resource :me, controller: :me
      resource :password
      resources :accounts
      resources :users
      resources :notification_tokens, only: :create
    end
  end

  # User account
  devise_for :users,
    controllers: {
      masquerades: "jumpstart/masquerades",
      omniauth_callbacks: "users/omniauth_callbacks",
      registrations: "users/registrations",
      sessions: "users/sessions"
    }
  devise_scope :user do
    get "session/otp", to: "sessions#otp"
  end

  resources :announcements, only: [:index]
  resources :api_tokens
  resources :accounts do
    member do
      patch :switch
    end

    resource :transfer, module: :accounts
    resources :account_users, path: :members
    resources :account_invitations, path: :invitations, module: :accounts
  end
  resources :account_invitations

  # Payments
  resource :card
  resource :subscription do
    patch :info
    patch :pause
    patch :resume
  end
  resources :charges

  namespace :account do
    resource :password
  end
  resources :notifications, only: [:index, :show]
  namespace :users do
    resources :mentions, only: [:index]
  end
  namespace :user, module: :users do
    resource :two_factor, controller: :two_factor do
      get :backup_codes
      get :verify
    end
    resources :connected_accounts
  end

  namespace :action_text do
    resources :embeds, only: [:create], constraints: {id: /[^\/]+/} do
      collection do
        get :patterns
      end
    end
  end

  scope controller: :static do
    get :about
    get :terms
    get :privacy
    get :pricing
  end

  post :sudo, to: "users/sudo#create"

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "dashboard#show", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end

  # Public marketing homepage
  root to: "static#index"
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!

  def edit
    if Jumpstart.config.stripe?
      @setup_intent = current_account.processor&.stripe? ? current_account.payment_processor.create_setup_intent : Stripe::SetupIntent.create
    end
  end

  def update
    current_account.assign_attributes(processor: processor)
    current_account.update_card(token)
    redirect_to subscription_path, notice: t(".updated")
  end

  private

  def card_params
    params.require(:account).permit(:card_token, :processor)
  end

  def token
    card_params.fetch("card_token")
  end

  def processor
    card_params.fetch("processor")
  end
end

app/views/cards/edit.html.erb
<div class="flex flex-wrap my-4 lg:px-4">
  <div class="lg:w-1/4 w-full p-4">
    <%= render partial: "shared/account_navbar" %>
  </div>

  <div class="lg:w-3/4 w-full p-4">
    <div class="lg:p-10 p-4 bg-white rounded-lg border border-gray-300">
      <h1 class="h2 mb-2"><%= link_to t(".billing"), subscription_path, class: "text-primary hover:underline" %> / <%= t(".payment_details") %></h2>

      <% if current_account.paypal? %>
        <%#= link_to "Change source", "https://www.paypal.com/us/smarthelp/article/faq1414", class: "btn btn-link text-gray-700", target: "_blank", rel: "nofollow noopener" %>
        <%= render 'cards/forms/paypal'    if Jumpstart.config.paypal? %>
      <% else %>
        <%= render 'cards/forms/stripe', button: "Update Card", url: card_path, method: :put, setup_intent: @setup_intent if Jumpstart.config.stripe? %>
        <%= render 'cards/forms/braintree' if Jumpstart.config.braintree? %>
        <%= render 'cards/forms/paddle' if Jumpstart.config.paddle? %>
      <% end %>
    </div>
  </div>
</div>